# Generated by Django 3.2.7 on 2021-09-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='uploads'),
        ),
    ]
